services:
  sentiment-trigger-creation:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: >
      python3 -m autoprompt.create_trigger 
      --train glue_data/SST-2/train.tsv 
      --dev glue_data/SST-2/dev.tsv 
      --template '<s> {sentence} [T] [T] [T] [P] . </s>' 
      --label-map '{"0": ["Ġworse", "Ġincompetence", "ĠWorse", "Ġblamed", "Ġsucked"], "1": ["ĠCris", "Ġmarvelous", "Ġphilanthrop", "Ġvisionary", "Ġwonderful"]}' 
      --num-cand 100 
      --accumulation-steps 30 
      --bsz 24 
      --eval-size 48 
      --iters 20 
      --model-name roberta-large
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]